export const MOVIES_IS_FETCHING = "MOVIES_IS_FETCHING";
export const MOVIES_FETCH_SUCCESS = "MOVIES_FETCH_SUCCESS";
export const MOVIES_FETCH_ERROR = "MOVIES_FETCH_ERROR";
export const GENRES_IS_FETCHING = "GENRES_IS_FETCHING";
export const GENRES_FETCH_SUCCESS = "GENRES_FETCH_SUCCESS";
export const GENRES_FETCH_ERROR = "GENRES_FETCH_ERROR";
